/* Generated By:JJTree: Do not edit this line. ASTcheck_constraint_expression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.google.cloud.solutions.spannerddl.parser;

import com.google.cloud.solutions.spannerddl.diff.ASTTreeUtils;

public class ASTcheck_constraint_expression extends SimpleNode {

  public ASTcheck_constraint_expression(int id) {
    super(id);
  }

  public ASTcheck_constraint_expression(DdlParser p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
    return ASTTreeUtils.tokensToString(firstToken, lastToken);
  }
}
/* JavaCC - OriginalChecksum=1dec56d1166086c490dec3256315d282 (do not edit this line) */
