/* Generated By:JJTree: Do not edit this line. ASTexpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.google.cloud.solutions.spannerddl.parser;

import com.google.cloud.solutions.spannerddl.diff.ASTTreeUtils;

public class ASTexpression extends SimpleNode {

  public ASTexpression(int id) {
    super(id);
  }

  public ASTexpression(DdlParser p, int id) {
    super(p, id);
  }

  @Override
  public String toString() {
    return ASTTreeUtils.tokensToString(this.firstToken, this.lastToken);
  }
}
/* JavaCC - OriginalChecksum=70d81a28578367794ced22b054b7898b (do not edit this line) */
