/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated by: JJTree: Do not edit this line. ASTforeign_key.java Version 1.1 */
/* ParserGeneratorCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.google.cloud.solutions.spannerddl.parser;

import com.google.common.base.Joiner;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

public class ASTforeign_key extends SimpleNode {

  public static final String ANONYMOUS_NAME = "ANONYMOUS_FOREIGN_KEY_NOT_SUPPORTED";

  public ASTforeign_key(int id) {
    super(id);
  }

  public ASTforeign_key(DdlParser p, int id) {
    super(p, id);
  }

  public String getName() {
    // name is optional
    if (children[0] instanceof ASTconstraint_name) {
      return ((ASTconstraint_name) children[0]).jjtGetFirstToken().toString();
    } else {
      return ANONYMOUS_NAME;
    }
  }

  public List<String> getConstrainedColumnNames() {
    return identifierListToStringList(
        (ASTidentifier_list) ((ASTreferencing_columns) children[1]).children[0]);
  }

  private List<String> identifierListToStringList(ASTidentifier_list idList) {
    return Arrays.stream(idList.children)
        .map(o -> ((ASTidentifier) o).jjtGetFirstToken().toString())
        .collect(Collectors.toList());
  }

  public String getReferencedTableName() {
    int child = 1;
    if (children[0] instanceof ASTconstraint_name) {
      child++;
    }
    return ((ASTreferenced_table) children[child]).jjtGetFirstToken().toString();
  }

  public List<String> getReferencedColumnNames() {
    int child = 2;
    if (children[0] instanceof ASTconstraint_name) {
      child++;
    }
    return identifierListToStringList(
        (ASTidentifier_list) ((ASTreferenced_columns) children[child]).children[0]);
  }

  public String toString() {

    return "CONSTRAINT "
        + getName()
        + " FOREIGN KEY ("
        + Joiner.on(", ").join(getConstrainedColumnNames())
        + ") REFERENCES "
        + getReferencedTableName()
        + " ("
        + Joiner.on(", ").join(getReferencedColumnNames())
        + ")";
  }

  @Override
  public boolean equals(Object other) {
    if (other instanceof ASTforeign_key) {
      return this.toString().equals(other.toString());
    }
    return false;
  }

  public static Comparator<ASTforeign_key> SORT_BY_NAME_COMPARATOR =
      Comparator.comparing(ASTforeign_key::getName);
}
/* ParserGeneratorCC - OriginalChecksum=fd7ef99f8a377f60dbefa483a915186f (do not edit this line) */
